### ISSUE TITLE
Throw nicer error when electric car profiles do not sum up to 100

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etengine#1148]
When trying to the set following input values:
```
transport_car_using_electricity_home_charging_share: 0.0
transport_car_using_electricity_hybrid_charging_share: 0.0
transport_car_using_electricity_fast_charging_share: 0.0
transport_car_using_electricity_regular_charging_share: 0.0
transport_car_using_electricity_smart_charging_share: 0.0
```
the model returns a very long error. Is it possible to turn this into something more informative?
```

{
    "errors": [
        "undefined method `rotate' for nil:NilClass\n/var/www/etengine/releases/20201224150144/app/models/qernel/causality/curves.rb:30:in `rotate'\n/var/www/etengine/releases/20201224150144/app/models/qernel/causality/curves.rb:21:in `curve'\n/var/www/etengine/releases/20201224150144/app/models/qernel/merit_facade/curves.rb:31:in `curve'\n/var/www/etengine/releases/20201224150144/app/models/qernel/merit_facade/consumer_adapter.rb:60:in `consumption_profile'\n/var/www/etengine/releases/20201224150144/app/models/qernel/merit_facade/consumer_adapter.rb:35:in `participant'\n/var/www/etengine/releases/20201224150144/app/models/qernel/plugins/simple_merit_order.rb:99:in `block in setup'\n/var/www/etengine/releases/20201224150144/app/models/qernel/plugins/simple_merit_order.rb:119:in `block in each_adapter'\n/var/www/etengine/releases/20201224150144/app/models/qernel/plugins/simple_merit_order.rb:119:in `each'\n/var/www/etengine/releases/20201224150144/app/models/qernel/plugins/simple_merit_order.rb:119:in `each_adapter'\n/var/www/etengine/releases/20201224150144/app/models/qernel/plugins/simple_merit_order.rb:94:in `setup'\n/var/www/etengine/releases/20201224150144/app/models/qernel/merit_facade/manager.rb:18:in `setup'\n/var/www/etengine/releases/20201224150144/app/models/qernel/plugins/causality.rb:58:in `setup'\n/var/www/etengine/releases/20201224150144/app/models/qernel/plugins/plugin.rb:28:in `block in trigger'\n/var/www/etengine/releases/20201224150144/app/models/qernel/plugins/plugin.rb:26:in `each'\n/var/www/etengine/releases/20201224150144/app/models/qernel/plugins/plugin.rb:26:in `trigger'\n/var/www/etengine/releases/20201224150144/app/models/qernel/lifecycle.rb:79:in `block in with_callback'\n/var/www/etengine/releases/20201224150144/app/models/qernel/lifecycle.rb:78:in `each_value'\n/var/www/etengine/releases/20201224150144/app/models/qernel/lifecycle.rb:78:in `with_callback'\n/var/www/etengine/releases/20201224150144/app/models/qernel/lifecycle.rb:26:in `calculate'\n/var/www/etengine/releases/20201224150144/app/models/qernel/graph.rb:338:in `calculate'\n/var/www/etengine/releases/20201224150144/app/models/gql/gql.rb:289:in `calculate_graphs'\n/var/www/etengine/releases/20201224150144/app/models/gql/gql.rb:214:in `block in prepare'\n/var/www/etengine/releases/20201224150144/lib/instrumentable.rb:5:in `block in instrument'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/notifications.rb:168:in `block in instrument'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/notifications/instrumenter.rb:23:in `instrument'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/notifications.rb:168:in `instrument'\n/var/www/etengine/releases/20201224150144/lib/instrumentable.rb:4:in `instrument'\n/var/www/etengine/releases/20201224150144/app/models/gql/gql.rb:214:in `prepare'\n/var/www/etengine/releases/20201224150144/app/models/scenario.rb:171:in `gql'\n/var/www/etengine/releases/20201224150144/app/serializers/scenario_update_serializer.rb:71:in `perform_gqueries!'\n/var/www/etengine/releases/20201224150144/app/serializers/scenario_update_serializer.rb:12:in `initialize'\n/var/www/etengine/releases/20201224150144/app/controllers/api/v3/scenarios_controller.rb:197:in `new'\n/var/www/etengine/releases/20201224150144/app/controllers/api/v3/scenarios_controller.rb:197:in `block in update'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'\n/home/deploy/.rbenv/versions/2.6.6/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:212:in `transaction'\n/var/www/etengine/releases/20201224150144/app/controllers/api/v3/scenarios_controller.rb:194:in `update'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/abstract_controller/base.rb:194:in `process_action'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_controller/metal/rendering.rb:30:in `process_action'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/abstract_controller/callbacks.rb:42:in `block in process_action'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:109:in `block in run_callbacks'\n/var/www/etengine/releases/20201224150144/app/controllers/api/v3/scenarios_controller.rb:305:in `block in wrap_with_raven_context'\n/var/www/etengine/releases/20201224150144/app/models/api/v3/scenario_raven_context.rb:28:in `block (2 levels) in with_context'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/sentry-raven-2.13.0/lib/raven/instance.rb:201:in `extra_context'\n/home/deploy/.rbenv/versions/2.6.6/lib/ruby/2.6.0/forwardable.rb:230:in `extra_context'\n/var/www/etengine/releases/20201224150144/app/models/api/v3/scenario_raven_context.rb:27:in `block in with_context'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/sentry-raven-2.13.0/lib/raven/instance.rb:186:in `tags_context'\n/home/deploy/.rbenv/versions/2.6.6/lib/ruby/2.6.0/forwardable.rb:230:in `tags_context'\n/var/www/etengine/releases/20201224150144/app/models/api/v3/scenario_raven_context.rb:26:in `with_context'\n/var/www/etengine/releases/20201224150144/app/controllers/api/v3/scenarios_controller.rb:305:in `wrap_with_raven_context'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `block in run_callbacks'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/sentry-raven-2.13.0/lib/raven/integrations/rails/controller_transaction.rb:7:in `block in included'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `instance_exec'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `block in run_callbacks'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:136:in `run_callbacks'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/abstract_controller/callbacks.rb:41:in `process_action'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_controller/metal/rescue.rb:22:in `process_action'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/notifications.rb:168:in `block in instrument'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/notifications/instrumenter.rb:23:in `instrument'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/notifications.rb:168:in `instrument'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_controller/metal/instrumentation.rb:32:in `process_action'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/railties/controller_runtime.rb:24:in `process_action'\n/var/www/etengine/releases/20201224150144/app/controllers/api/v3/base_controller.rb:35:in `process_action'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/abstract_controller/base.rb:134:in `process'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/actionview-5.2.4.4/lib/action_view/rendering.rb:32:in `process'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_controller/metal.rb:191:in `dispatch'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_controller/metal.rb:252:in `dispatch'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/routing/route_set.rb:34:in `serve'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/journey/router.rb:52:in `block in serve'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/journey/router.rb:35:in `each'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/journey/router.rb:35:in `serve'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/routing/route_set.rb:840:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/newrelic_rpm-4.7.1.340/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/newrelic_rpm-4.7.1.340/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/newrelic_rpm-4.7.1.340/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/warden-1.2.8/lib/warden/manager.rb:36:in `block in call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/warden-1.2.8/lib/warden/manager.rb:34:in `catch'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/warden-1.2.8/lib/warden/manager.rb:34:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/newrelic_rpm-4.7.1.340/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/newrelic_rpm-4.7.1.340/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/newrelic_rpm-4.7.1.340/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:40:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/newrelic_rpm-4.7.1.340/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/newrelic_rpm-4.7.1.340/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/http/content_security_policy.rb:18:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/newrelic_rpm-4.7.1.340/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/newrelic_rpm-4.7.1.340/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/cookies.rb:670:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/newrelic_rpm-4.7.1.340/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:98:in `run_callbacks'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/callbacks.rb:26:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/newrelic_rpm-4.7.1.340/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/newrelic_rpm-4.7.1.340/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/newrelic_rpm-4.7.1.340/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/rack/logger.rb:38:in `call_app'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/rack/logger.rb:26:in `block in call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/tagged_logging.rb:71:in `block in tagged'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/tagged_logging.rb:28:in `tagged'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/tagged_logging.rb:71:in `tagged'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/rack/logger.rb:26:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/newrelic_rpm-4.7.1.340/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/newrelic_rpm-4.7.1.340/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/request_id.rb:27:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/newrelic_rpm-4.7.1.340/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/newrelic_rpm-4.7.1.340/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/newrelic_rpm-4.7.1.340/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/newrelic_rpm-4.7.1.340/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/executor.rb:14:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/newrelic_rpm-4.7.1.340/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/static.rb:127:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/newrelic_rpm-4.7.1.340/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/newrelic_rpm-4.7.1.340/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/sentry-raven-2.13.0/lib/raven/integrations/rack.rb:51:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/newrelic_rpm-4.7.1.340/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/engine.rb:524:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/railtie.rb:190:in `public_send'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/railtie.rb:190:in `method_missing'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/newrelic_rpm-4.7.1.340/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/rack-cors-1.0.5/lib/rack/cors.rb:98:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/newrelic_rpm-4.7.1.340/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/puma-3.12.6/lib/puma/configuration.rb:227:in `call'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/puma-3.12.6/lib/puma/server.rb:706:in `handle_request'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/puma-3.12.6/lib/puma/server.rb:476:in `process_client'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/puma-3.12.6/lib/puma/server.rb:334:in `block in run'\n/var/www/etengine/shared/bundle/ruby/2.6.0/gems/puma-3.12.6/lib/puma/thread_pool.rb:135:in `block in spawn_thread'"
    ]
}
```

**Comment by antw** [comment]
I've fixed the error when generating an aggregate profile when all shares are zero, but shouldn't these inputs belong to an ETSource share group?

**Comment by michieldenhaan** [comment]
Thanks! Yes, they should be! I'll fix that ASAP. A client managed to set them all to zero using the API without getting an error. When I tried to do the same I got this big error. So I was a bit puzzled how they managed to do this, but the inputs not being in a share group explains that I guess.
