### ISSUE TITLE
Beta scenario for derived dataset doesn't load

### ISSUE THREAD

**Issue by grdw** [quintel/etengine#923]
As seen by @jorisberkhout 

Steps to reproduce

1. Open https://beta-pro.energytransitionmodel.com
2. Pick a derived dataset from the list
3. Click start

Stacktrace ETEngine beta server:

````
NoMethodError (undefined method `+' for nil:NilClass):
  app/models/qernel/plugins/merit/aggregate_curve.rb:57:in `balanced_mix'
  app/models/qernel/plugins/merit/aggregate_curve.rb:17:in `build'
  app/models/qernel/plugins/merit/curves.rb:40:in `ev_demand'
  app/models/qernel/plugins/merit/curves.rb:20:in `public_send'
  app/models/qernel/plugins/merit/curves.rb:20:in `block in combined'
  app/models/qernel/plugins/merit/curves.rb:20:in `map'
  app/models/qernel/plugins/merit/curves.rb:20:in `combined'
  app/models/qernel/plugins/merit_order.rb:93:in `total_demand'
  app/models/qernel/plugins/simple_merit_order.rb:94:in `total_demand_curve'
  app/models/qernel/plugins/merit_order.rb:83:in `total_demand_curve'
  app/models/qernel/plugins/simple_merit_order.rb:81:in `setup'
  app/models/qernel/plugins/merit_order.rb:67:in `setup'
  app/models/qernel/plugins/plugin.rb:28:in `block in trigger'
  app/models/qernel/plugins/plugin.rb:26:in `each'
  app/models/qernel/plugins/plugin.rb:26:in `trigger'
  app/models/qernel/lifecycle.rb:62:in `block in with_callback'
````

**Comment by grdw** [comment]
Possible problem is that the `electric_vehicle_profile_x_share`'s are missing from the `*.derived.ad` files in ETSource.

**Comment by jorisberkhout** [comment]
> Possible problem is that the electric_vehicle_profile_x_share's are missing from the *.derived.ad files in ETSource.

Most likely yes. I am testing this locally.

**Comment by jorisberkhout** [comment]
That indeed seems to be the problem. Solution is in https://github.com/quintel/etsource/pull/1274

**Comment by antw** [comment]
Thanks @jorisberkhout. I will add an Atlas validation to assert that each dataset has these values present.
