### ISSUE TITLE
GQL error

### ISSUE THREAD

**Issue by grdw** [quintel/etengine#986]
```
I, [2018-01-08T12:16:40.148088 #12050]  INFO -- : [691669a0-c341-48d5-b2ae-a85d8ace2e46] Completed 401 Unauthorized in 145ms (ActiveRecord: 1.8ms)
F, [2018-01-08T12:16:40.148892 #12050] FATAL -- : [691669a0-c341-48d5-b2ae-a85d8ace2e46]
F, [2018-01-08T12:16:40.148918 #12050] FATAL -- : [691669a0-c341-48d5-b2ae-a85d8ace2e46] Gql::CommandError ((eval):1: trailing `_' in number
lambda { Q(1990_in_co2_emission) }
                ^
(eval):1: syntax error, unexpected tIDENTIFIER, expecting ')'
ambda { Q(1990_in_co2_emission) }
                              ^):
F, [2018-01-08T12:16:40.148933 #12050] FATAL -- : [691669a0-c341-48d5-b2ae-a85d8ace2e46]
F, [2018-01-08T12:16:40.148968 #12050] FATAL -- : [691669a0-c341-48d5-b2ae-a85d8ace2e46] app/models/gql/command.rb:36:in `to_proc'
[691669a0-c341-48d5-b2ae-a85d8ace2e46] app/models/gql/query_interface/base.rb:58:in `rubel_execute'
[691669a0-c341-48d5-b2ae-a85d8ace2e46] app/models/gql/query_interface/base.rb:20:in `query'
[691669a0-c341-48d5-b2ae-a85d8ace2e46] app/models/gql/gql.rb:332:in `query_present'
[691669a0-c341-48d5-b2ae-a85d8ace2e46] app/models/gql/gql.rb:323:in `query_standard'
[691669a0-c341-48d5-b2ae-a85d8ace2e46] app/models/gql/gql.rb:188:in `block in query_with_modifier'
[691669a0-c341-48d5-b2ae-a85d8ace2e46] lib/instrumentable.rb:5:in `block in instrument'
[691669a0-c341-48d5-b2ae-a85d8ace2e46] lib/instrumentable.rb:4:in `instrument'
[691669a0-c341-48d5-b2ae-a85d8ace2e46] app/models/gql/gql.rb:186:in `query_with_modifier'
[691669a0-c341-48d5-b2ae-a85d8ace2e46] app/models/gql/gql.rb:161:in `query'
[691669a0-c341-48d5-b2ae-a85d8ace2e46] app/controllers/data/gqueries_controller.rb:19:in `test'
```

**Comment by grdw** [comment]
Fixed it, appearantly all queries starting with a number, in the example above:

`Q(1990_in_co2_emission)` should be quoted: `Q("1990_in_co2_emission")`.
