### ISSUE TITLE
Dataset at PR: https://github.com/quintel/etsource/pull/1534/files#submit-review doesn't work

### ISSUE THREAD

**Issue by grdw** [quintel/etengine#990]
Related: https://github.com/quintel/etsource/pull/1534

Error:

```
RuntimeError - No Atlas data for "s_heer_hendrikskinderen" at /xxx/xxx/xxx/etengine/tmp/atlas/s_heer_hendrikskinderen.pack:
  app/models/etsource/atlas_loader.rb:33:in `load'
  app/models/etsource/dataset/import.rb:84:in `load_graph_dataset'
  app/models/etsource/dataset/import.rb:72:in `load_dataset_hash'
  app/models/etsource/dataset/import.rb:52:in `import'
  app/models/etsource/dataset.rb:24:in `import'
  app/models/etsource/loader.rb:62:in `block (2 levels) in dataset'
  app/models/etsource/loader.rb:110:in `block in cache'
  app/models/etsource/loader.rb:109:in `cache'
  app/models/etsource/loader.rb:61:in `block in dataset'
  lib/instrumentable.rb:5:in `block in instrument'
  lib/instrumentable.rb:4:in `instrument'
  app/models/etsource/loader.rb:60:in `dataset'
  app/models/gql/gql.rb:74:in `initialize'
```

I'm guessing that this only happens localhost, but it's a bit worrying.

**Comment by grdw** [comment]
Hmmm.. it almost looks as though ETEngine doesn't automatically refresh the content in ETsource 🤔

**Comment by grdw** [comment]
Turns out I'm an idiot.
